# Inserts a blank line between shell prompts
add_newline = true

# Which is equivalent to
format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$elm\
$java\
$nodejs\
$scala\
$nix_shell\
$memory_usage\
$azure\
$env_var\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""
